#!/bin/bash

#name: webapi
#short: Create a new dotnet WebAPI

# update the app name if a valid name
export APP_NAME=$1
export APP_LOWER=$(echo "$APP_NAME" | tr '[:upper:]' '[:lower:]')

if [[ "$APP_NAME" =~ ^[A-Z][A-Za-z][A-Za-z][A-Za-z][A-Za-z]+$ ]]
then
    if [ -d "$APP_LOWER" ]
    then
        echo "Directory $APP_LOWER already exists"
        exit 1
    fi

    git pull
    git clone https://github.com/retaildevcrews/dotnet-webapi-template "$APP_LOWER"
    cd "$APP_LOWER" || exit

    kubectl delete -R -f deploy --wait=false --ignore-not-found=true

    rm -rf .devcontainer
    rm -rf .git
    rm -rf .github
    rm -f .gitignore
    rm -f LICENSE
    rm -f curl.sh

    mv src/csapp.csproj "src/$APP_LOWER.csproj"

    sed -i "s/csapp/$APP_LOWER/g" .kic/commands/test-integration
    sed -i "s/csapp/$APP_LOWER/g" .kic/commands/test-load
    sed -i "s/csapp/$APP_LOWER/g" .kic/commands/build/app
    sed -i "s/csapp/$APP_LOWER/g" .kic/commands/build/webv
    sed -i "s/csapp/$APP_LOWER/g" .kic/commands/cluster/clean
    sed -i "s/csapp/$APP_LOWER/g" .kic/commands/cluster/deploy
    sed -i "s/csapp/$APP_LOWER/g" .kic/commands/cluster/bootstrap

    sed -i "s~deploy/apps~apps~g" autogitops/config.json
    sed -i "s/csapp/$APP_LOWER/g" Dockerfile
    find . -name '*.*' -type f -exec sed -i "s/CSApp/$APP_NAME/g" {} \;
    find . -name '*.*' -type f -exec sed -i "s/csapp/$APP_LOWER/g" {} \;
    dotnet restore src

    kic build app
    kic build webv

    kubectl delete ns monitoring --ignore-not-found=true --wait=false
    kubectl delete ns logging --ignore-not-found=true --wait=true --timeout=30s

    kic cluster bootstrap

    kubectl wait pod -l app="$APP_LOWER" -n "$APP_LOWER" --for condition=ready --timeout 30s
    kubectl wait pod -l app=webv -n "$APP_LOWER" --for condition=ready --timeout 30s

    kic test integration > /dev/null

    echo ""
    echo ""
    echo ""
    echo "running load test"
    kic test load &

    # give the load test time to start
    sleep 5

    echo ""
    echo ""
    echo "running integration test"
    kic test integration
    echo ""

else
    echo "Invalid App Name $1"
fi
